name: CI actions
on:
  pull_request:
    branches:
      - main

jobs:
  run-eslint:
    runs-on: ubuntu-latest

    steps:
      - name: actions-checkout
        uses: actions/checkout@v3
      - name: eslint-check
        run: |
          yarn install  
          yarn lint

  build:
    runs-on: ubuntu-latest
    needs: [run-eslint]

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn build

  tests:
    runs-on: ubuntu-latest
    needs: [run-eslint]

    steps:
      - uses: actions/checkout@v3
      - name: Tests running
        run: |
          yarn install
          yarn test
